version: "3.9"

services:
  mariadb:
    image: mariadb:10.8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql

  redis:
    image: redis:alpine

  bench:
    image: frappe/bench:latest
    command: >
      bash -c 'if [ ! -f /init.sh ]; then
        echo "Fetching init.sh…" &&
        wget -qO /init.sh https://raw.githubusercontent.com/frappe/crm/develop/docker/init.sh &&
        chmod +x /init.sh
      fi &&
      bash /init.sh'
    working_dir: /home/frappe
    depends_on:
      - mariadb
      - redis
    environment:
      - SHELL=/bin/bash
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - SITE_NAME=${SITE_NAME}
    volumes:
      - bench-sites:/home/frappe/frappe-bench
    labels:
      - traefik.enable=true
      - "traefik.http.routers.crm.rule=Host(`${SITE_NAME}`)"
      - traefik.http.routers.crm.entrypoints=websecure
      - traefik.http.routers.crm.tls.certresolver=letsencrypt
      - traefik.http.services.crm.loadbalancer.server.port=8000

volumes:
  mariadb-data:
  bench-sites:
